# -*- coding: utf-8 -*-
"""Letters_Count.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MSSdcgmDfBfgzLmcc4yt5sXttos2Vm6C
"""

#Count the number of each letter in a sentence.


abc = input("give me sentence?")
def Letters_Count(abc):
    dict = {}
    for n in abc:
        keys = dict.keys()
        if n in keys:
            dict[n] += 1
        else:
            dict[n] = 1
    return dict
print(Letters_Count(abc))